# Generated by Django 3.2.7 on 2021-09-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, default=None, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('dialog', models.TextField(default='start')),
                ('temp', models.TextField(default='')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('hyperlink', models.BooleanField(default=True)),
            ],
        ),
    ]
